# Generated by Django 5.0.8 on 2025-09-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("teacher", models.CharField(max_length=100)),
                ("scripture_reference", models.CharField(blank=True, max_length=100)),
                ("date_created", models.DateField()),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="teachings/pdfs/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("series", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bible Study, Sermon Notes, Devotional",
                        max_length=50,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Teaching",
                "verbose_name_plural": "Teachings",
                "ordering": ["-date_created"],
            },
        ),
    ]
