# Generated by Django 5.0.8 on 2025-09-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_teaching"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="from_google_calendar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="google_calendar_id",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="google_calendar_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
