# Generated by Django 5.0.8 on 2025-09-17 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_event_from_google_calendar_event_google_calendar_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churchinfo",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="churchinfo",
            name="youtube_url",
        ),
    ]
