# Generated by Django 5.0.8 on 2025-09-17 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_churchinfo_instagram_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ministry",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
