# Generated by Django 5.0.8 on 2025-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_delete_ministry_delete_resource_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                (
                    "content",
                    models.TextField(help_text="Newsletter content (HTML supported)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("author", models.CharField(default="Church Admin", max_length=100)),
                ("recipients_count", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Newsletter Issue",
                "verbose_name_plural": "Newsletter Issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameModel(
            old_name="Newsletter",
            new_name="NewsletterSubscriber",
        ),
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
            },
        ),
    ]
